/**
 * WebSocket real-time layer — live dashboard updates from MediBrain.
 *
 * Events pushed to connected clients:
 * - vitals:updated — new vital signs recorded
 * - acuity:changed — patient acuity score recalculated
 * - alert:created — new alert generated
 * - alert:acknowledged — alert acknowledged by nurse
 * - task:completed — nurse completed a task
 * - task:created — new order/task created
 * - assignment:updated — nurse assignment changed
 * - handoff:generated — shift handoff report ready
 * - record:minted — new Record NFT minted on Solana
 * - scribe:generated — SOAP note generated by MediScribe
 *
 * Clients subscribe to channels based on their role:
 * - admin → all events
 * - nurse → events for assigned patients only
 * - doctor → events for their patients only
 * - patient → events for their own records only
 */

export type WSEventType =
  | 'vitals:updated'
  | 'acuity:changed'
  | 'alert:created'
  | 'alert:acknowledged'
  | 'task:completed'
  | 'task:created'
  | 'assignment:updated'
  | 'handoff:generated'
  | 'record:minted'
  | 'scribe:generated'
  | 'system:health'
  | 'blockchain:tx';

export interface WSEvent {
  type: WSEventType;
  patientId?: string;
  nurseId?: string;
  data: unknown;
  timestamp: string;
}

export interface WSSubscription {
  clientId: string;
  role: string;
  pubkey: string;
  channels: WSEventType[];
  patientFilter?: string[]; // Only receive events for these patients
}

/**
 * In-memory event bus for WebSocket broadcasting.
 *
 * NOTE: This implementation is intentionally in-memory for single-server deployments.
 * For multi-server scaling, replace with Redis pub/sub (e.g., ioredis) and move
 * the event history buffer to a Redis stream or sorted set. The subscribe/publish
 * interface is designed to make that migration straightforward.
 */

/** Typed event payloads for each event type */
export interface WSEventPayloads {
  'vitals:updated': Record<string, number>;
  'acuity:changed': { oldScore: number; newScore: number; delta: number };
  'alert:created': { id: string; severity: string; message: string };
  'alert:acknowledged': { alertId: string; acknowledgedBy: string };
  'task:completed': { taskId: string };
  'task:created': { taskId: string; type: string; priority: string };
  'assignment:updated': { nurseId: string; patientIds: string[] };
  'handoff:generated': { reportId: string; fromNurse: string; toNurse: string };
  'record:minted': { recordId: string; signature: string };
  'scribe:generated': { sessionId: string; patientId: string };
  'system:health': { status: string; uptime: number };
  'blockchain:tx': { txType: string; signature: string };
}

const EVENT_HISTORY_MAX = 100;

export class EventBus {
  private subscribers: Map<string, WSSubscription> = new Map();
  private handlers: Map<string, Array<{ clientId: string; handler: (event: WSEvent) => void }>> = new Map();
  private eventHistory: Map<WSEventType, WSEvent[]> = new Map();

  /** Register a new WebSocket client */
  subscribe(sub: WSSubscription, handler: (event: WSEvent) => void): void {
    this.subscribers.set(sub.clientId, sub);

    for (const channel of sub.channels) {
      const channelHandlers = this.handlers.get(channel) ?? [];
      channelHandlers.push({ clientId: sub.clientId, handler });
      this.handlers.set(channel, channelHandlers);
    }
  }

  /** Remove a client subscription */
  unsubscribe(clientId: string): void {
    this.subscribers.delete(clientId);

    // Clean up handler references for this client
    for (const [channel, channelHandlers] of this.handlers) {
      this.handlers.set(
        channel,
        channelHandlers.filter((h) => h.clientId !== clientId),
      );
    }
  }

  /** Replay recent event history for a late subscriber */
  replayHistory(clientId: string): void {
    const sub = this.subscribers.get(clientId);
    if (!sub) return;

    const channelHandlers = new Map<string, (event: WSEvent) => void>();
    for (const [channel, handlers] of this.handlers) {
      const entry = handlers.find((h) => h.clientId === clientId);
      if (entry) channelHandlers.set(channel, entry.handler);
    }

    for (const channel of sub.channels) {
      const history = this.eventHistory.get(channel) ?? [];
      const handler = channelHandlers.get(channel);
      if (!handler) continue;

      for (const event of history) {
        // Respect patient filter
        if (sub.patientFilter && event.patientId && !sub.patientFilter.includes(event.patientId)) {
          continue;
        }
        try {
          handler(event);
        } catch {
          // Don't let replay errors break the subscription
        }
      }
    }
  }

  /** Publish an event to all matching subscribers */
  publish(event: WSEvent): void {
    // Store in history buffer
    const history = this.eventHistory.get(event.type) ?? [];
    history.push(event);
    if (history.length > EVENT_HISTORY_MAX) {
      history.shift();
    }
    this.eventHistory.set(event.type, history);

    // Broadcast to handlers
    const channelHandlers = this.handlers.get(event.type) ?? [];

    for (const { handler } of channelHandlers) {
      try {
        handler(event);
      } catch {
        // Don't let one bad handler break others
      }
    }
  }

  /** Get event history for a specific event type */
  getHistory(type: WSEventType, limit?: number): WSEvent[] {
    const history = this.eventHistory.get(type) ?? [];
    return limit ? history.slice(-limit) : [...history];
  }

  /** Emit a vitals update event */
  emitVitalsUpdate(patientId: string, vitals: Record<string, number>): void {
    this.publish({
      type: 'vitals:updated',
      patientId,
      data: vitals,
      timestamp: new Date().toISOString(),
    });
  }

  /** Emit an acuity change event */
  emitAcuityChange(patientId: string, oldScore: number, newScore: number): void {
    this.publish({
      type: 'acuity:changed',
      patientId,
      data: { oldScore, newScore, delta: newScore - oldScore },
      timestamp: new Date().toISOString(),
    });
  }

  /** Emit a new alert event */
  emitAlert(patientId: string, alert: { id: string; severity: string; message: string }): void {
    this.publish({
      type: 'alert:created',
      patientId,
      data: alert,
      timestamp: new Date().toISOString(),
    });
  }

  /** Emit a task completion event */
  emitTaskCompleted(patientId: string, nurseId: string, taskId: string): void {
    this.publish({
      type: 'task:completed',
      patientId,
      nurseId,
      data: { taskId },
      timestamp: new Date().toISOString(),
    });
  }

  /** Emit a blockchain transaction event */
  emitBlockchainTx(type: string, signature: string, patientId?: string): void {
    this.publish({
      type: 'blockchain:tx',
      patientId,
      data: { txType: type, signature },
      timestamp: new Date().toISOString(),
    });
  }

  /** Get subscriber count */
  getSubscriberCount(): number {
    return this.subscribers.size;
  }
}

/** Singleton event bus instance */
export const eventBus = new EventBus();
